/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author MOON
 */
public class JFrameNutricionista extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMenuPrincipal
     */
    public JFrameNutricionista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAlimentos = new javax.swing.JMenu();
        jAltaAlimento = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        JmenuPacientes = new javax.swing.JMenu();
        jAltaPaciente = new javax.swing.JMenu();
        jMenuDietas = new javax.swing.JMenu();
        jAltaDieta = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 868, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        jMenuAlimentos.setText("Alimentos");
        jMenuAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlimentosActionPerformed(evt);
            }
        });

        jAltaAlimento.setText("Alta Alimento");
        jAltaAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAltaAlimentoActionPerformed(evt);
            }
        });
        jMenuAlimentos.add(jAltaAlimento);

        jMenuItem1.setText("jMenuItem1");
        jMenuAlimentos.add(jMenuItem1);

        jMenuBar1.add(jMenuAlimentos);

        JmenuPacientes.setText("Pacientes");

        jAltaPaciente.setText("Alta Paciente");
        jAltaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAltaPacienteActionPerformed(evt);
            }
        });
        JmenuPacientes.add(jAltaPaciente);

        jMenuBar1.add(JmenuPacientes);

        jMenuDietas.setText("Dietas");

        jAltaDieta.setText("Alta Dieta");
        jAltaDieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAltaDietaActionPerformed(evt);
            }
        });
        jMenuDietas.add(jAltaDieta);

        jMenuBar1.add(jMenuDietas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAltaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAltaPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAltaPacienteActionPerformed

    private void jMenuAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlimentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAlimentosActionPerformed

    private void jAltaAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAltaAlimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAltaAlimentoActionPerformed

    private void jAltaDietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAltaDietaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAltaDietaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameNutricionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameNutricionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameNutricionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameNutricionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameNutricionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JmenuPacientes;
    private javax.swing.JMenu jAltaAlimento;
    private javax.swing.JMenu jAltaDieta;
    private javax.swing.JMenu jAltaPaciente;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenuAlimentos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDietas;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
