/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Alimentos;
import Persistencia.AlimentoData;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FrancoPC
 */
public class VistaAlimento extends javax.swing.JPanel {

    private AlimentoData alimentoData;
    
    public VistaAlimento() {
        initComponents();
        alimentoData = new AlimentoData();
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfCodComida = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfCalorias = new javax.swing.JTextField();
        jtfDetalle = new javax.swing.JTextField();
        jcbTipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAlimento = new javax.swing.JTable();
        jbEditar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jbBusca = new javax.swing.JButton();
        jbNuevo2 = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 2000));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Franco\\ULP\\02. Materias\\1°Año\\2°Cuatrimestre\\Lab. de Programación\\6-Proyecto Final\\Proyect_Final\\--PROYECTO-de-la-REALIDAD--NUTRICIONISTA\\--PROYECTO-de-la-REALIDAD--NUTRICIONISTA\\NUTRICIONISTAPROYECTOFINALG15\\src\\imagenes\\Alimento.png")); // NOI18N
        jLabel1.setText("ALIMENTO");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Código De La Comida:");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Calorias (por 100mg):");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Detalle:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Tipo:");

        jtfCodComida.setBackground(null);
        jtfCodComida.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jtfCodComida.setForeground(new java.awt.Color(0, 0, 0));

        jtfNombre.setBackground(null);
        jtfNombre.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jtfNombre.setForeground(new java.awt.Color(0, 0, 0));
        jtfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNombreKeyTyped(evt);
            }
        });

        jtfCalorias.setBackground(null);
        jtfCalorias.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jtfCalorias.setForeground(new java.awt.Color(0, 0, 0));

        jtfDetalle.setBackground(null);
        jtfDetalle.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jtfDetalle.setForeground(new java.awt.Color(0, 0, 0));
        jtfDetalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDetalleKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfDetalleKeyTyped(evt);
            }
        });

        jcbTipo.setBackground(null);
        jcbTipo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jcbTipo.setForeground(new java.awt.Color(0, 0, 0));
        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Común", "Sin TACC", "Deslactosada" }));
        jcbTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbTipoItemStateChanged(evt);
            }
        });
        jcbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoActionPerformed(evt);
            }
        });

        jtAlimento.setBackground(null);
        jtAlimento.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jtAlimento.setForeground(new java.awt.Color(0, 0, 0));
        jtAlimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Calorías", "Tipo", "Detalle"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtAlimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtAlimentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtAlimento);
        if (jtAlimento.getColumnModel().getColumnCount() > 0) {
            jtAlimento.getColumnModel().getColumn(0).setMinWidth(50);
            jtAlimento.getColumnModel().getColumn(0).setMaxWidth(50);
            jtAlimento.getColumnModel().getColumn(1).setMinWidth(130);
            jtAlimento.getColumnModel().getColumn(1).setMaxWidth(130);
            jtAlimento.getColumnModel().getColumn(2).setMinWidth(60);
            jtAlimento.getColumnModel().getColumn(2).setMaxWidth(60);
            jtAlimento.getColumnModel().getColumn(3).setMinWidth(70);
            jtAlimento.getColumnModel().getColumn(3).setMaxWidth(70);
            jtAlimento.getColumnModel().getColumn(4).setMinWidth(290);
            jtAlimento.getColumnModel().getColumn(4).setMaxWidth(290);
        }

        jbEditar.setBackground(new java.awt.Color(51, 153, 0));
        jbEditar.setIcon(new javax.swing.ImageIcon("D:\\Franco\\ULP\\02. Materias\\1°Año\\2°Cuatrimestre\\Lab. de Programación\\6-Proyecto Final\\Proyect_Final\\--PROYECTO-de-la-REALIDAD--NUTRICIONISTA\\--PROYECTO-de-la-REALIDAD--NUTRICIONISTA\\NUTRICIONISTAPROYECTOFINALG15\\src\\imagenes\\editar.png")); // NOI18N
        jbEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbGuardar.setBackground(new java.awt.Color(51, 153, 0));
        jbGuardar.setIcon(new javax.swing.ImageIcon("D:\\Franco\\ULP\\02. Materias\\1°Año\\2°Cuatrimestre\\Lab. de Programación\\6-Proyecto Final\\Proyect_Final\\--PROYECTO-de-la-REALIDAD--NUTRICIONISTA\\--PROYECTO-de-la-REALIDAD--NUTRICIONISTA\\NUTRICIONISTAPROYECTOFINALG15\\src\\imagenes\\guardar.png")); // NOI18N
        jbGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbBorrar.setBackground(new java.awt.Color(51, 153, 0));
        jbBorrar.setIcon(new javax.swing.ImageIcon("D:\\Franco\\ULP\\02. Materias\\1°Año\\2°Cuatrimestre\\Lab. de Programación\\6-Proyecto Final\\Proyect_Final\\--PROYECTO-de-la-REALIDAD--NUTRICIONISTA\\--PROYECTO-de-la-REALIDAD--NUTRICIONISTA\\NUTRICIONISTAPROYECTOFINALG15\\src\\imagenes\\tacho.png")); // NOI18N
        jbBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jbBusca.setBackground(new java.awt.Color(0, 153, 0));
        jbBusca.setIcon(new javax.swing.ImageIcon("D:\\Franco\\ULP\\02. Materias\\1°Año\\2°Cuatrimestre\\Lab. de Programación\\6-Proyecto Final\\Proyect_Final\\--PROYECTO-de-la-REALIDAD--NUTRICIONISTA\\--PROYECTO-de-la-REALIDAD--NUTRICIONISTA\\NUTRICIONISTAPROYECTOFINALG15\\src\\imagenes\\lupa.png")); // NOI18N
        jbBusca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscaActionPerformed(evt);
            }
        });

        jbNuevo2.setBackground(new java.awt.Color(51, 153, 0));
        jbNuevo2.setIcon(new javax.swing.ImageIcon("D:\\Franco\\ULP\\02. Materias\\1°Año\\2°Cuatrimestre\\Lab. de Programación\\6-Proyecto Final\\Proyect_Final\\--PROYECTO-de-la-REALIDAD--NUTRICIONISTA\\--PROYECTO-de-la-REALIDAD--NUTRICIONISTA\\NUTRICIONISTAPROYECTOFINALG15\\src\\imagenes\\nuevo.png")); // NOI18N
        jbNuevo2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbNuevo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfCodComida, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(jtfNombre)
                            .addComponent(jtfCalorias)
                            .addComponent(jtfDetalle, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbEditar))
                    .addComponent(jbBusca)
                    .addComponent(jbNuevo2)
                    .addComponent(jbBorrar))
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfCodComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jtfDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbBusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbNuevo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBorrar)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoActionPerformed
       
    }//GEN-LAST:event_jcbTipoActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        modificar();
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        guardar();
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        eliminar();
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jbBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscaActionPerformed
        if (!(jtfNombre.getText().isEmpty())&&jtfCodComida.getText().isEmpty()&&jtfCalorias.getText().isEmpty()&&jtfDetalle.getText().isEmpty()&&jcbTipo.getSelectedIndex()==0) {
            buscarNombre();
            
        } else if (jtfNombre.getText().isEmpty()&&jtfCodComida.getText().isEmpty()&&jtfCalorias.getText().isEmpty()&&!(jtfDetalle.getText().isEmpty())&&jcbTipo.getSelectedIndex()==0) {
            buscarDetalle();
            
        } else if (jtfNombre.getText().isEmpty()&&jtfCodComida.getText().isEmpty()&&jtfCalorias.getText().isEmpty()&&jtfDetalle.getText().isEmpty()&&!(jcbTipo.getSelectedIndex()==0)){
            buscarTipo();
        }
    }//GEN-LAST:event_jbBuscaActionPerformed

    private void jbNuevo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevo2ActionPerformed
        limpiar();
    }//GEN-LAST:event_jbNuevo2ActionPerformed

    private void jtAlimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtAlimentoMouseClicked
        if (evt.getClickCount()==2) {
            int alimento = jtAlimento.getSelectedRow();
            
            jtfCodComida.setText(jtAlimento.getValueAt(alimento, 0).toString());
            jtfNombre.setText(jtAlimento.getValueAt(alimento, 1).toString());
            jtfCalorias.setText(jtAlimento.getValueAt(alimento, 2).toString());
            jcbTipo.setSelectedItem(jtAlimento.getValueAt(alimento, 3).toString());
            jtfDetalle.setText(jtAlimento.getValueAt(alimento, 4).toString());
        }
    }//GEN-LAST:event_jtAlimentoMouseClicked

    private void jtfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyTyped
        
    }//GEN-LAST:event_jtfNombreKeyTyped

    private void jtfDetalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDetalleKeyTyped
        
    }//GEN-LAST:event_jtfDetalleKeyTyped

    private void jtfDetalleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDetalleKeyPressed
        
    }//GEN-LAST:event_jtfDetalleKeyPressed

    private void jtfNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreKeyPressed
        
    }//GEN-LAST:event_jtfNombreKeyPressed

    private void jcbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbTipoItemStateChanged

    }//GEN-LAST:event_jcbTipoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbBusca;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo2;
    private javax.swing.JComboBox<String> jcbTipo;
    private javax.swing.JTable jtAlimento;
    private javax.swing.JTextField jtfCalorias;
    private javax.swing.JTextField jtfCodComida;
    private javax.swing.JTextField jtfDetalle;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables

    private void buscarNombre(){
        try {
            String nombreComida = jtfNombre.getText();
            List<Alimentos> alimento = alimentoData.buscarAlimentoPorNombre(nombreComida);
            
            
            
            DefaultTableModel model = (DefaultTableModel) jtAlimento.getModel();
            model.setRowCount(0);
            
            for (Alimentos alimentos : alimento) {
                
                model.addRow(new Object[]{
                    
                alimentos.getCodComida(),
                alimentos.getNombreComida(),
                alimentos.getCaloriasPorPorcion(),
                alimentos.getStipoComida(),
                alimentos.getDetalle()
                });
            }
            
            if (alimento.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron alimentos.");
                
            }
            
         } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Código no válido.");
        }
  }
    
        private void buscarDetalle(){
        try {
            String detalleComida = jtfDetalle.getText();
            List<Alimentos> alimento = alimentoData.buscarAlimentoPorDetalle(detalleComida);
                       
            DefaultTableModel model = (DefaultTableModel) jtAlimento.getModel();
            model.setRowCount(0);
            
            for (Alimentos alimentos : alimento) {
                
                model.addRow(new Object[]{
                    
                alimentos.getCodComida(),
                alimentos.getNombreComida(),
                alimentos.getCaloriasPorPorcion(),
                alimentos.getStipoComida(),
                alimentos.getDetalle()
                });
            }
            
             
            if (alimento.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron alimentos.");
                
            }
            
         } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Código no válido.");
        }
    }
        
            private void buscarTipo(){
        try {
            String tipoComida = jcbTipo.getSelectedItem().toString();
            List<Alimentos> alimento = alimentoData.buscarAlimentoPorTipo(tipoComida);
            
           
            
            DefaultTableModel model = (DefaultTableModel) jtAlimento.getModel();
            model.setRowCount(0);
            
            for (Alimentos alimentos : alimento) {
                
                model.addRow(new Object[]{
                    
                alimentos.getCodComida(),
                alimentos.getNombreComida(),
                alimentos.getCaloriasPorPorcion(),
                alimentos.getStipoComida(),
                alimentos.getDetalle()
                });
            }
            
             if (alimento.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No se encontraron alimentos.");
                
            }
            
         } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Código no válido.");
        }
    }

    public void limpiar(){
    
        jtfCodComida.setText("");
        jtfNombre.setText("");
        jtfDetalle.setText("");
        jtfCalorias.setText("");
        jcbTipo.setSelectedIndex(0);
    }
    
    
    private void guardar(){
        try {
            int codComida = Integer.parseInt(jtfCodComida.getText());
            String nombre = jtfNombre.getText();
            int calorias = Integer.parseInt(jtfCalorias.getText());
            String tipo = (String) jcbTipo.getSelectedItem();
            String detalle = jtfDetalle.getText();

            Alimentos alimento = new Alimentos(codComida,nombre, calorias, tipo, detalle);
            alimentoData.guardarAlimento(alimento);
            JOptionPane.showMessageDialog(this, "Alimento guardado exitosamente.");
            actualizarTabla();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en el ingreso de datos.");
        }    
    }
    
    private void modificar(){
        
        try {
            int codComida = Integer.parseInt(jtfCodComida.getText());
            String nombre = jtfNombre.getText();
            int calorias = Integer.parseInt(jtfCalorias.getText());
            String tipo = (String) jcbTipo.getSelectedItem();
            String detalle = jtfDetalle.getText();

            Alimentos alimento = new Alimentos(codComida, nombre, calorias, tipo, detalle);
            alimentoData.actualizarAlimento(alimento);
            JOptionPane.showMessageDialog(this, "Alimento modificado exitosamente.");
            actualizarTabla();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Código no válido.");
        }
    }  
    
    private void eliminar(){
        try {
             int codComida = Integer.parseInt(jtfCodComida.getText());
            alimentoData.eliminarAlimento(codComida);
            JOptionPane.showMessageDialog(this, "Alimento eliminado exitosamente.");
            actualizarTabla();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Código no válido.");
        }
    }
    
    private void actualizarTabla() {
        
        DefaultTableModel model = (DefaultTableModel) jtAlimento.getModel();
        model.setRowCount(0);
        
        for (Alimentos alimento : alimentoData.listarAlimentos()) {
            model.addRow(new Object[]{
                alimento.getCodComida(),
                alimento.getNombreComida(),
                alimento.getCaloriasPorPorcion(),
                alimento.getStipoComida(),
                alimento.getDetalle()
            });
        }
    }
}
